[package]
name = "gameserver"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder.workspace = true
tokio.workspace = true
server_config.workspace = true
sonettobuf.workspace = true
bytes.workspace = true
