[package]
name = "httpserver"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web.workspace = true
flate2.workspace = true
openssl.workspace = true
serde_json.workspace = true
server_config.workspace = true
